// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlrfgyhtaxpgceastgyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRscmZneWh0YXhwZ2NlYXN0Z3l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxNjI1NzIsImV4cCI6MjA3NTczODU3Mn0.ByncuDm2w-O1mMmCeA7gmgwf0qDbHyta6QWnsoe9QbA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});